config/routes.rb
Rails.application.routes.draw do
  # resources :directions
  # resources :ingredients
  resources :recipes
  root to: 'recipes#index'
  
  get   'about', to: 'static_pages#about'
  get   'contact', to: 'static_pages#contact'
  get   'privacy', to: 'static_pages#privacy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id          :integer          not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_recipes_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :directions, dependent: :destroy

  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true
  accepts_nested_attributes_for :directions,
                                reject_if: proc { |attributes| attributes['step'].blank? },
                                allow_destroy: true

  validates :title, :description, :image, presence: true

  has_one_attached :image
  # has_attached_file :image, styles: { :medium => "400x400#" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show]
  # GET /recipes or /recipes.json
  def index
    # @recipes = Recipe.all
    @recipe = Recipe.all.order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    # @recipe = Recipe.new(recipe_params)
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :step, input_html: { class: 'form-input form-control' }
    = link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
  - if @recipe.errors.any?
    #errors
      %p
        = @recipe.errors.count
        Prevented this recipe froms saving
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, input_html: { class: 'form-control' }
    = f.input :image, input_html: { class: 'form-control' }

  .row
    .col-md-6
      %h3 Ingredients
      #ingredients
        = f.simple_fields_for :ingredients do |ingredient|
          = render 'ingredient_fields', f: ingredient
        .links
          = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

    .col-md-6
      %h3 Directions
      #directions
        = f.simple_fields_for :directions do |direction|
          = render 'direction_fields', f: direction
        .links
          = link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

  = f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :name, input_html: { class: 'form-input form-control' }
    = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Title:</strong>
    <%= recipe.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
  .row
    - recipes.each do |recipe|
      .col-md-4
        .recipe
          .image_wrapper
            = link_to recipe do
              = image_tag recipe.image
          %h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image, class: "recipe_image"
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        %p.description= @recipe.description
        %p
          Submitted by
          = @recipe.user.email

  .row
    .col-md-6
      #ingredients
        %h2 Ingredients
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li= ingredient.name

    .col-md-6
      #directions
        %h2 Directions
        %ul
          - @recipe.directions.each do |direction|
            %li= direction.step

  .row
    .col-md-12
      = link_to "Back", root_path, class: "btn btn-default"
      - if user_signed_in?
        = link_to "Edit", edit_recipe_path, class: "btn btn-default"
        = button_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"